// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAODoJVi1rvLSvTKXpplvI-H0VydjDPjQ',
    appId: '1:789124782904:web:af354ba4c165d6b1153fcd',
    messagingSenderId: '789124782904',
    projectId: 'abir-portfolio-d9482',
    authDomain: 'abir-portfolio-d9482.firebaseapp.com',
    storageBucket: 'abir-portfolio-d9482.appspot.com',
    measurementId: 'G-5Q2MDMR64N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Au2ARG6HUvJG_AkbjkdoHK6ydMua0UA',
    appId: '1:789124782904:android:43c17342b4ddf31c153fcd',
    messagingSenderId: '789124782904',
    projectId: 'abir-portfolio-d9482',
    storageBucket: 'abir-portfolio-d9482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGS7YgLK3p9PjFtSruQKDMOk5bLPOL6fM',
    appId: '1:789124782904:ios:d82e2677cd1ad4ad153fcd',
    messagingSenderId: '789124782904',
    projectId: 'abir-portfolio-d9482',
    storageBucket: 'abir-portfolio-d9482.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );
}
